datos = {}
datos["Nombre"] = input("Escribe el nombre: ")
print("Diccionario actualizado:", datos)
datos["Edad"] = input("Escribe la edad: ")
print("Diccionario actualizado:", datos)
datos["Sexo"] = input("Escribe el sexo: ")
print("Diccionario actualizado:", datos)
datos["Teléfono"] = input("Escribe el número de teléfono: ")
print("Diccionario actualizado:", datos)
datos["Dirección"] = input("Escribe la dirección: ")
print("Diccionario final:", datos)
input()